name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - 'release/v*'

env:
  NODE_VERSION: '20'

jobs:
  prepare:
    name: Prepare Metadata
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      is_release: ${{ steps.vars.outputs.is_release }}
      deploy_env: ${{ steps.vars.outputs.deploy_env }}
    steps:
      - id: vars
        run: |
          # 1. Prepare short SHA (7 characters)
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          DATE=$(date +'%Y%m%d')

          # 2. Determine Environment & Version
          if [[ "${{ github.ref }}" == refs/heads/release/v* ]]; then
            VERSION=${GITHUB_REF#refs/heads/release/}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "deploy_env=staging" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            echo "version=${BRANCH_NAME}-${DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "deploy_env=dev" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Checks
        run: |
          npm run format:check
          npm run lint
          npm run type-check
          npm run build

  deploy:
    name: Deploy to ${{ needs.prepare.outputs.deploy_env }}
    needs: [prepare, build]
    # Only run if not production (Production has its own job for approval)
    if: needs.prepare.outputs.deploy_env != 'prod'
    uses: ./.github/workflows/build-docker-and-deploy-reusable.yml
    with:
      environment: ${{ needs.prepare.outputs.deploy_env }}
      image-tag: ${{ needs.prepare.outputs.version }}
    secrets: inherit

  create_tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [prepare, deploy]
    if: needs.prepare.outputs.is_release == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ needs.prepare.outputs.version }}
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git ${{ needs.prepare.outputs.version }}

  deploy_prod:
    name: Deploy to Production
    needs: [prepare, deploy]
    if: needs.prepare.outputs.is_release == 'true'
    uses: ./.github/workflows/build-docker-and-deploy-reusable.yml
    with:
      environment: prod
      image-tag: ${{ needs.prepare.outputs.version }}
    secrets: inherit
